[env:bluepill_f103c6]
platform = ststm32
board = bluepill_f103c6
framework = spl
build_flags =
    -Iinclude
    -DSTM32F10X_LD
    -DUSE_STDPERIPH_DRIVER
lib_extra_dirs = lib
monitor_speed = 115200
upload_protocol = stlink
