[env:bluepill_f103c6]
platform = ststm32
board = bluepill_f103c8
framework = spl
build_flags =
    -DSTM32F10X_LD
    -DUSE_STDPERIPH_DRIVER
board_upload.maximum_size = 32768
board_upload.maximum_ram_size = 10240
monitor_speed = 115200
upload_protocol = stlink
